site_name: 'Yixiang Gao'

nav:
  - 'Home': 'index.md'
  - 'Blogs': blogs/index.md
  - 'Publications': 'https://scholar.google.com/citations?user=7104qXwAAAAJ&hl=en'
  - 'CV': assets/YixiangGao_CV.pdf

theme:
  name: material
  logo: assets/images/YG.svg
  favicon: assets/images/YG.svg
  palette:
    primary: indigo

plugins:
  - search
  - blog:
      blog_dir: blogs

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.mark
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/g1y5x3
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/gao_yixiang

extra_css:
  - assets/extra.css

exclude_docs: |
  plans/

copyright: Copyright &copy; 2025 Yixiang Gao
