site_name: 'Yixiang Gao'

nav:
  - 'Home': 'index.md'
  - 'Publications': 'https://scholar.google.com/citations?user=7104qXwAAAAJ&hl=en'
  - 'CV': assets/YixiangGao_CV.pdf
  # - 'Blog': 'blog/index.md'

theme:
  name: material
  logo: assets/images/YG.svg
  favicon: assets/images/YG.svg
  palette:
    primary: indigo

plugins:
  - search
  - blog

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.mark

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/g1y5x3
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/gao_yixiang

extra_css:
  - assets/extra.css

copyright: Copyright &copy; 2025 Yixiang Gao
